name: dsci522
channels:
  - conda-forge
dependencies:
  - altair[version='=5.5.0']
  - ipykernel=6.29.5
  - jupyterlab=4.3.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - pip=24.3.1
  - python=3.11
  - scikit-learn=1.5.2
  - pandera=0.20.2
  - quarto=1.5.57
  - click=8.1.7
  - tabulate=0.9.0
  - requests=2.32.3
  - pip:
    - vegafusion==1.6.9
    - vegafusion-python-embed==1.6.9
    - vl-convert-python==1.7.0
    - deepchecks==0.18.1